name: Go_Workflow
on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v2


      - name: Set up Go_Workflow
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'


      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v
